#!/bin/sh

# turn wifi on (because we turn it off to use dock NIC when docked)
# NOTE: increase sleep to 12 at the end of the script before starting Chrome
# nmcli radio wifi on

# set scaling
gsettings set org.gnome.settings-daemon.plugins.xsettings overrides "[{'Gdk/WindowScalingFactor', <2>}]"
gsettings set org.gnome.desktop.interface scaling-factor 2

## It would be awesome to be able to use this because a scale factor of 2
## is a bit too big, unfortunately there is a bug and I cannot access 
## the right and bottom of the screen as noted on the Arch Wiki under HiDPI
## Bug: https://bugs.freedesktop.org/show_bug.cgi?id=39949
#xrandr --output eDP-1 --scale 1.35x1.35 --fb 4320x2430

# use only the laptop display, set resolution automatically
xrandr --output eDP-1 --auto

# set screen brightness to 15%
gdbus call --session --dest org.gnome.SettingsDaemon.Power --object-path /org/gnome/SettingsDaemon/Power --method org.freedesktop.DBus.Properties.Set org.gnome.SettingsDaemon.Power.Screen Brightness "<int32 50>"

# Chrome needs to be restarted to respect new scaling settings
# need to sleep for a few seconds for it to finish closing
# added additional sleep time to ensure wifi is usually reconnected
# before Chrome restarts
#/usr/bin/pkill --oldest --signal TERM -f chrome
#sleep 8
#google-chrome &
